name: Update ICS feed

on:
  schedule:
    - cron: "0 9 * * *"   # daily at 09:00 UTC
  workflow_dispatch:       # allow manual runs

# Make sure the workflow can push back to the repo
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install requests beautifulsoup4 ics

      - name: Ensure docs folder exists
        run: mkdir -p docs

      - name: Run generator
        run: python generat
