name: Update ICS feed

on:
  schedule:
    - cron: "0 9 * * *"  # Every day at 9:00 UTC
  workflow_dispatch:      # Allows manual runs

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: pip install requests beautifulsoup4 ics
      - name: Run script
        run: python ruha_events.py
      - name: Commit and push results
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add docs/ruha.ics
          git commit -m "Update ruha.ics" || echo "No changes"
          git push
